[build]
builder = "nixpacks"
buildCommand = "npm install --omit=dev"

[deploy]
startCommand = "node server/server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[nixpacks]
nodeVersion = "20"
